# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.NTS.8.4
PackageVersion: 8.4.26
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php84
UpgradeBehavior: install
ReleaseDate: 2026-09-22
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.26-nts-Win32-vs17-x64.zip
    InstallerSha256: da68394f9193b7f6b89d0c76861a4034ae10efee7fd55a7255d8118c2acf70d7
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.26-nts-Win32-vs17-x86.zip
    InstallerSha256: 82dbaa361e035237a6ed0ade126f837798c7bf0565610b73ddb40986fc107128
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
