# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.NTS.8.3
PackageVersion: 8.3.35
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php83
UpgradeBehavior: install
ReleaseDate: 2026-09-22
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.3.35-nts-Win32-vs16-x64.zip
    InstallerSha256: 25a8e2ac9ff30f1d768d1447c09a600617fa6e6082729f6e95f008b59c91fe45
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.3.35-nts-Win32-vs16-x86.zip
    InstallerSha256: 3021dcdd0432df641537ca193b0766dac18debc27d81f4dd9dc49240d04e6f75
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
