# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.8.4
PackageVersion: 8.4.25
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php84
UpgradeBehavior: install
ReleaseDate: 2026-08-25
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.25-Win32-vs17-x64.zip
    InstallerSha256: 2cf521fb6bcb45b634c7e9a7ab2afb6d41698b987bbc73c4975d90a065e0f16c
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.25-Win32-vs17-x86.zip
    InstallerSha256: 92cb92b350cd513ee7aa5c32ce2aaa2e082fb04beaf7baa9b3703b7c0de32f0b
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
