# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.8.3
PackageVersion: 8.3.32
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php83
UpgradeBehavior: install
ReleaseDate: 2026-07-01
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.3.32-Win32-vs16-x64.zip
    InstallerSha256: 76fe1eafda6dcc8927122adb79088b22e19cfbf81c3dbed44ccb335d1bf8de29
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.3.32-Win32-vs16-x86.zip
    InstallerSha256: fc3033f013636fa6b8d274d6e68e5a1704a155d64faa91c55b484883fdc6b071
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
