# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.8.5
PackageVersion: 8.5.8
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php85
UpgradeBehavior: install
ReleaseDate: 2026-07-01
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.5.8-Win32-vs17-x64.zip
    InstallerSha256: a7323e50a1e29fddc278d9297ca9a4ec134bd1cca5396af39115284a125cab2f
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.5.8-Win32-vs17-x86.zip
    InstallerSha256: 86a01ec179c6aba884e72b8b399589b6aab7749ee6bf782adb8c335f7c756778
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
