# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.NTS.8.4
PackageVersion: 8.4.25
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php84
UpgradeBehavior: install
ReleaseDate: 2026-08-25
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.25-nts-Win32-vs17-x64.zip
    InstallerSha256: 43a8f67ed2e5223fafb21293c85976361808855405278cef2cf3037c3ae2529c
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.25-nts-Win32-vs17-x86.zip
    InstallerSha256: 07ad87d7bf37798468c85a54b4c48189bd4f7561390432aad1502f6afb9cdbfe
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
