# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PHP.PHP.NTS.8.5
PackageVersion: 8.5.10
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php85
UpgradeBehavior: install
ReleaseDate: 2026-08-25
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.5.10-nts-Win32-vs17-x64.zip
    InstallerSha256: 22ec430195984d233eb9e62c637a945bbcda06efca2f392d9d96d62c6acd34f8
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.5.10-nts-Win32-vs17-x86.zip
    InstallerSha256: de135a1dec0cca14d47865c957cf6dc40286a7859704488e153042b500387776
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.12.0
