# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PHP.PHP.8.4
PackageVersion: 8.4.9
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php84
UpgradeBehavior: install
ReleaseDate: 2025-07-01
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://windows.php.net/downloads/releases/php-8.4.9-Win32-vs17-x64.zip
    InstallerSha256: dbc8819ece58661e50e146cb20dba27ff88ab361a37a07b364b8baf80d9edbb4
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://windows.php.net/downloads/releases/php-8.4.9-Win32-vs17-x86.zip
    InstallerSha256: 67e1301b747529999036703561d434b7b7f118aeaa4f906b2d3735afe561bdaf
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.10.0
