# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: PHP.PHP.8.3
PackageVersion: 8.3.18
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php83
UpgradeBehavior: install
ReleaseDate: 2025-03-11
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://windows.php.net/downloads/releases/php-8.3.18-Win32-vs16-x64.zip
    InstallerSha256: 868afabe640b0a721846d269d50bae391abe8363f1e3b31b2f1a123a89077ec2
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://windows.php.net/downloads/releases/php-8.3.18-Win32-vs16-x86.zip
    InstallerSha256: c0f7c627c97f99f65e84465a832a9c39c4e110882f2ea6ef6f5dd8a8ce99adce
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.9.0
